import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Description from "../components/Description";
import Reservations from "../components/Reservations";
import Map from "../components/Map";
import React, { Component } from "react";
import Reviews from "../components/Review";
const post = (props) => {
  console.log(props);
  return <p>My post link params</p>;
};
post.getInitialProps = ({ query }) => {
  return { myParams: query };
};

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      property: {
        title: "",
        host: "",
        specs: "",
        about: "",
        space: "",
        guest: "",
        other: "",
        amenities: [],
      },
    };
  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Description property={this.state.property} />

        <Map property={this.state.property} />

        <Reservations />
      </div>
    );
  }
}
